apiVersion: apps/v1
kind: Deployment
metadata:
  name: bbdp
  labels:
    app: busybox
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: radial/busyboxplus:curl
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']
        ports:
        - containerPort: 9376
          protocol: TCP
        - containerPort: 9376
          protocol: UDP
